name: Test

on:
  push:
    paths:
    - 'action.yml'
    - 'index.js'
    - 'package.json'
    - 'package-lock.json'
    - 'node_modules/**'
    - '.github/workflows/test.yml'

jobs:
  debug1:
    runs-on: ubuntu-latest
    name: Check commands
    steps:
      - uses: actions/checkout@v4
      - uses: ./
      - run: |
          sudo apt search pacman
          repo-add --version
