name: Test

on:
  push:
    branches:
    - main
    paths:
    - 'action.yml'
    - 'index.js'
    - 'package.json'
    - 'package-lock.json'
    - 'node_modules/**'
    - '.github/workflows/test.yml'
  pull_request:
    paths:
    - 'action.yml'
    - 'index.js'
    - 'package.json'
    - 'package-lock.json'
    - 'node_modules/**'
    - '.github/workflows/test.yml'

jobs:
  debug1:
    runs-on: ubuntu-24.04
    name: Check commands
    steps:
      - uses: actions/checkout@v4
      - uses: ./
      - run: |
          for cmd in pacman \
                     pacman-conf \
                     makepkg \
                     pacman-key \
                     repo-add \
                     repo-elephant \
                     repo-remove; do
            type ${cmd}
            ${cmd} --version
          done
